apiVersion: v1
kind: Service
metadata:
    name: word-game-service
spec:
    selector:
        app: word-game
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
